name: SCEs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy=2.2.3
  - pandas=2.2.3
  - scikit-learn=1.7.1
  - scipy=1.14.1
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - pytest=8.4.2
  - pip:
      - python-Levenshtein==0.26.1
      - regex==2024.11.6
      - torch==2.5.1
      - transformers==4.49.0
      - datasets==3.3.1
      - accelerate==1.4.0
      - textstat==0.7.10
      - sentencepiece==0.2.0